### ISSUE TITLE
建议：对首页格言设置自动适配宽度

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#186]
我的简单实现是
```css
@media screen and (max-width: 5000px) {
    h1#theFirstPageSayContent {
        font-size: 4em;
    }
}

@media screen and (max-width: 2000px) {
    h1#theFirstPageSayContent {
        font-size: 3.5em;
    }
}

@media screen and (max-width: 1000px) {
    h1#theFirstPageSayContent {
        font-size: 3em;
    }
}

@media screen and (max-width: 480px) {
    h1#theFirstPageSayContent {
        font-size: 2em;
    }
}

@media screen and (max-width: 340px) {
    h1#theFirstPageSayContent {
        font-size: 1.5em;
    }
}
```
希望作者能给出更好的支持百分比的实现方式
ヾ(◍°∇°◍)ﾉﾞ
