### ISSUE TITLE
建议在Footer处新增网安备案填写处

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#191]
在```/footer.php```约19行部分，我进行了以下修改
```html
<div class="footer-copyright">
    <span class="copyright-mdx">Theme: MDx By <a href="https://flyhigher.top" target="_blank" class="click">AxtonYao</a></span>
    <span>
        <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802035663" target="_blank">
            <img src="https://i1-qiniu.s.ahdark.com/202108/18/6c0c61857bc13.png/index.webp" alt="网安备案"/>
            京公网安备 11010802035663号
        </a>
    </span>
    <?php if(!empty(mdx_get_option('mdx_icp_num'))){?><div class="mdx-copyright"><a href="https://beian.miit.gov.cn/" rel="noopener" target="_blank" class="click"><?php echo mdx_get_option('mdx_icp_num');?></a></div><?php }?>
</div>
```
并加入了以下样式
```css
.footer-copyright{
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
}
@media screen and (max-width: 700px){
    .footer-copyright{
        flex-direction: column;
    }
}
```
以此达到添加网安备案号的效果

![1629281403130.png](https://i1-qiniu.s.ahdark.com/202108/18/64954341ab031.png/index.webp)

实际添加不复杂，网安备案号的设置添加可以使用正则表达式提取数字部分或直接填写2个设置项，注意前边的小图标必须要添加（建议转换Base64）
