### ISSUE TITLE
极度建议 ImgBox的透明度

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#194]
新增以下样式即可
```css
#img-box {
  background-color: rgba(36,36,36,0.8)
}
```
不然看着太难受，而且这样方便阅读
