### ISSUE TITLE
点击文章图片访问文章页面&增加哀悼功能

### ISSUE THREAD

**Issue by yjn140** [yrccondor/mdx#219]
1. 希望是点击文章图片,也能访问文章页面

2. 增加哀悼功能,可定时开启,全局css

   ```css
   html {
       filter: progid:DXImageTransform.Microsoft.BasicImage(grayscale=1);
       -webkit-filter: grayscale(100%);
   	}
   ```
